/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/reports/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/accounts` | `/accounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `/reports/daily-book`; params?: Router.UnknownInputParams; } | { pathname: `/settings/backup`; params?: Router.UnknownInputParams; } | { pathname: `/vouchers/create`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/reports/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/accounts` | `/accounts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownOutputParams; } | { pathname: `/reports/daily-book`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/backup`; params?: Router.UnknownOutputParams; } | { pathname: `/vouchers/create`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/reports/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/accounts${`?${string}` | `#${string}` | ''}` | `/accounts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sales${`?${string}` | `#${string}` | ''}` | `/sales${`?${string}` | `#${string}` | ''}` | `/reports/daily-book${`?${string}` | `#${string}` | ''}` | `/settings/backup${`?${string}` | `#${string}` | ''}` | `/vouchers/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/reports/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/accounts` | `/accounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `/reports/daily-book`; params?: Router.UnknownInputParams; } | { pathname: `/settings/backup`; params?: Router.UnknownInputParams; } | { pathname: `/vouchers/create`; params?: Router.UnknownInputParams; };
    }
  }
}
