// ─── Database TypeScript Interfaces ──────────────────────────────────────────
// Strict types that mirror the Supabase `accounts` table exactly.
// Import these across Server Actions, Server Components, and Client Components
// to guarantee end-to-end type safety.

// ─── Enum ─────────────────────────────────────────────────────────────────────
// Mirrors account_type_enum in 001_accounts_schema.sql
export type AccountType =
  | 'Cash Account'
  | 'Bank Account'
  | 'Suppliers'
  | 'Customers'
  | 'Staff'
  | 'Expense Account'
  | 'Income Account'
  | 'Investors'
  | 'Inventory'
  | 'Assets Account'
  | 'Movable & Non Movable Property';

export const ACCOUNT_TYPE_VALUES: AccountType[] = [
  'Cash Account',
  'Bank Account',
  'Suppliers',
  'Customers',
  'Staff',
  'Expense Account',
  'Income Account',
  'Investors',
  'Inventory',
  'Assets Account',
  'Movable & Non Movable Property',
];

// ─── Row Types ────────────────────────────────────────────────────────────────

/** Full row as returned by SELECT * FROM accounts */
export interface Account {
  id:             string;        // UUID
  account_type:   AccountType;
  account_title:  string;
  region:         string;
  contact_number: string | null;
  created_at:     string;        // ISO-8601 timestamp string from Supabase
  balance?:       number;        // Running ledger balance
  total_due?:     number;        // Computed unpaid due for Suppliers/Customers
}

/** Payload for INSERT — id and created_at are generated by the database */
export type AccountInsert = Omit<Account, 'id' | 'created_at'>;

/** Payload for UPDATE — all fields optional except id */
export type AccountUpdate = Partial<AccountInsert> & { id: string };

export type ActionResult<T = void> =
  | { success: true;  data: T }
  | { success: false; error: string };

// ─── Product Types ────────────────────────────────────────────────────────────

export type ProductCategory =
  | 'Solars'
  | 'Inverters'
  | 'Cables'
  | 'Batteries'
  | 'Accessories'
  | 'Breakers'
  | 'Mounting Structure'
  | 'VFD'
  | 'Pump/Motors'
  | 'Filters'
  | 'Misc';

export const PRODUCT_CATEGORY_VALUES: ProductCategory[] = [
  'Solars',
  'Inverters',
  'Cables',
  'Batteries',
  'Accessories',
  'Breakers',
  'Mounting Structure',
  'VFD',
  'Pump/Motors',
  'Filters',
  'Misc',
];

export type AccountingUnit = string;

export const ACCOUNTING_UNIT_VALUES: string[] = [
  'N/O',
  'Number',
  'Liter',
  'Kg',
  'KW',
  'Yard',
  'Meter',
  'Foot',
  'Roll',
  'Box',
  'Set',
  'Pair',
  'Watt',
  'Ampere',
  'Volt',
  'Area',
];

/** Full row as returned by SELECT * FROM products */
export interface Product {
  id:              string;        // UUID
  item_name:       string;
  accounting_unit: string;
  category:        ProductCategory;
  remarks:         string | null;
  created_at:      string;        // ISO-8601 timestamp string from Supabase
}

/** Payload for INSERT — id and created_at are generated by the database */
export type ProductInsert = Omit<Product, 'id' | 'created_at'>;

/** Payload for UPDATE — all fields optional except id */
export type ProductUpdate = Partial<ProductInsert> & { id: string };

// ─── Business Settings Types ──────────────────────────────────────────────────

/** Full row as returned by SELECT * FROM business_settings */
export interface BusinessSettings {
  id:                  string;        // UUID
  business_name:       string;
  logo_url:            string | null;
  owner_name:          string | null;
  phone:               string | null;
  email:               string | null;
  address:             string | null;
  region:              string | null;
  ntn_or_tax_id:       string | null;
  currency:            string;
  receipt_footer_note: string | null;
  books_start_date:    string | null;
  updated_at:          string;        // ISO-8601 timestamp string from Supabase
}

/** Payload for UPDATE — all fields optional except id */
export type BusinessSettingsUpdate = Partial<Omit<BusinessSettings, 'id' | 'updated_at'>> & { id: string };

// ─── Purchase Types ───────────────────────────────────────────────────────────

/** Full row as returned by SELECT * FROM purchases */
export interface Purchase {
  id:              string;        // UUID
  invoice_no:      string;
  item_name:       string;
  accounting_unit: string;
  quantity:        number;
  rate:            number;
  amount:          number;
  power_watt:      number | null;
  paidAmount:      number;
  remainingAmount: number;
  paymentStatus:   string;
  supplier_id:     string | null;
  supplier_name:   string | null;
  purchase_date:   string;        // ISO format YYYY-MM-DD
  remarks:         string | null;
  created_at:      string;        // ISO-8601 timestamp string from Supabase
}

/** Payload for INSERT — id, created_at, and invoice_no (auto-generated) are handled by DB */
export type PurchaseInsert = Omit<Purchase, 'id' | 'created_at' | 'paidAmount' | 'remainingAmount' | 'paymentStatus' | 'invoice_no'> & { invoice_no?: string };

/** Payload for UPDATE — all fields optional except id */
export type PurchaseUpdate = Partial<PurchaseInsert> & { id: string };

// ─── Payment Voucher Types ────────────────────────────────────────────────────

export interface PaymentAllocation {
  id: string;
  voucherId: string;
  purchaseId: string;
  allocatedAmount: number;
}

export interface PaymentVoucher {
  id: string;
  voucherNo: string;
  date: string;
  supplierId: string;
  supplierName: string;
  paidFromAccountId: string;
  paidFromAccountName: string;
  amount: number;
  paymentMode: string;
  reference: string | null;
  notes: string | null;
  createdAt: string;
  allocations?: PaymentAllocation[];
}

export type PaymentAllocationInsert = Omit<PaymentAllocation, 'id' | 'voucherId'>;

export type PaymentVoucherInsert = Omit<PaymentVoucher, 'id' | 'createdAt' | 'voucherNo' | 'allocations'> & {
  voucherNo?: string;
  allocations: PaymentAllocationInsert[];
};

// ─── Sales Types ──────────────────────────────────────────────────────────────

export interface Sale {
  id:                string;        // UUID
  invoice_no:        string;
  customer_id:       string | null; // UUID
  customer_name:     string | null;
  customer_phone:    string | null;
  customer_area:     string | null;
  reference:         string | null;
  sale_date:         string;        // YYYY-MM-DD
  subtotal:          number;
  discount_percent:  number;
  discount_amount:   number;
  net_total:         number;
  total_received:    number;
  remaining_balance: number;
  remarks:           string | null;
  created_at:        string;        // ISO timestamp
}

export type SaleInsert = Omit<Sale, 'id' | 'created_at' | 'invoice_no'> & {
  invoice_no?: string;
};

export type SaleUpdate = Partial<Omit<Sale, 'id'>> & { id: string };

export interface SaleItem {
  id:              string;        // UUID
  sale_id:         string;        // UUID
  item_name:       string;
  accounting_unit: string;
  power_watt:      number | null;
  quantity:        number;
  rate:            number;
  amount:          number;
  remarks:         string | null;
}

export type SaleItemInsert = Omit<SaleItem, 'id' | 'sale_id'>;

export interface SalePayment {
  id:                   string;        // UUID
  sale_id:              string;        // UUID
  payment_account_id:   string | null; // UUID
  payment_account_name: string;
  pay_date:             string;        // YYYY-MM-DD
  remarks:              string | null;
  amount:               number;
}

export type SalePaymentInsert = Omit<SalePayment, 'id' | 'sale_id'>;

export interface SaleOtherCredit {
  id:        string;        // UUID
  sale_id:   string;        // UUID
  item_name: string;
  quantity:  number;
  rate:      number;
  amount:    number;
  remarks:   string | null;
}

export type SaleOtherCreditInsert = Omit<SaleOtherCredit, 'id' | 'sale_id'>;

// Extended Sale representation with associated items, payments, and other credits
export interface SaleWithRelations extends Sale {
  sale_items?:          SaleItem[];
  sale_payments?:       SalePayment[];
  sale_other_credits?:  SaleOtherCredit[];
  voucher_allocations?: any[];
}

// ─── Voucher Management Types ────────────────────────────────────────────────

export type VoucherType =
  | 'Cash Receipt'
  | 'Cash Payment'
  | 'Bank Receipt'
  | 'Bank Payment'
  | 'General'
  | 'Contra Voucher';

export interface Voucher {
  id:                 string;        // UUID
  voucher_no:         string;
  voucher_type:       VoucherType;
  voucher_date:       string;        // YYYY-MM-DD
  main_account_id:    string;        // UUID
  main_account_name:  string;
  party_account_id:   string | null; // UUID
  party_account_name: string | null;
  direction:          'receipt' | 'payment';
  amount:             number;
  details:            string | null;
  remarks:            string | null;
  created_at:         string;        // ISO timestamp
}

export type VoucherInsert = Omit<Voucher, 'id' | 'created_at' | 'voucher_no'> & {
  voucher_no?: string;
};

export type VoucherUpdate = Partial<Omit<Voucher, 'id'>> & { id: string };

// ─── Journal Voucher Types ───────────────────────────────────────────────────

export interface JournalVoucher {
  id:           string;        // UUID
  voucher_no:   string;        // prefix 'JV-'
  voucher_date: string;        // YYYY-MM-DD
  remarks:      string | null;
  total_debit:  number;
  total_credit: number;
  created_at:   string;        // ISO timestamp
}

export type JournalVoucherInsert = Omit<JournalVoucher, 'id' | 'created_at' | 'voucher_no'> & {
  voucher_no?: string;
};

export type JournalVoucherUpdate = Partial<Omit<JournalVoucher, 'id'>> & { id: string };

export interface JournalVoucherLine {
  id:           string;        // UUID
  voucher_id:   string;        // UUID
  account_id:   string;        // UUID
  account_name: string;
  remarks:      string | null;
  debit:        number;
  credit:       number;
}

export type JournalVoucherLineInsert = Omit<JournalVoucherLine, 'id' | 'voucher_id'>;

export interface JournalVoucherWithRelations extends JournalVoucher {
  lines: JournalVoucherLine[];
}
